blank_issues_enabled: true
contact_links:
  - name: Start a discussion
    about: Our preferred starting point if you have any questions, suggestions or feature proposals.
    url: https://github.com/crowci/crow/discussions/new/choose
