FROM --platform=$BUILDPLATFORM docker.io/golang:1.23-alpine3.21 AS build

WORKDIR /src
COPY . .
ARG TARGETOS TARGETARCH CI_COMMIT_SHA CI_COMMIT_TAG CI_COMMIT_BRANCH
RUN apk add --no-cache -q just git
RUN --mount=type=cache,target=/root/.cache/go-build \
  --mount=type=cache,target=/go/pkg \
  just build-agent

FROM docker.io/alpine:3.21

RUN apk add -U --no-cache ca-certificates && \
  addgroup -g 1000 -S crow && \
  adduser -u 1000 -G crow -S crow && \
  mkdir -p /etc/crow && \
  ln -s /etc/crow /etc/woodpecker && \
  chown -R crow:crow /etc/crow /etc/woodpecker

ENV GODEBUG=netdns=go
# Internal setting do NOT change! Signals that crow is running inside a container
ENV WOODPECKER_IN_CONTAINER=true
EXPOSE 3000

COPY --from=build /src/dist/crow-agent /bin/

HEALTHCHECK CMD ["/bin/crow-agent", "ping"]
ENTRYPOINT ["/bin/crow-agent"]
