FROM --platform=$BUILDPLATFORM docker.io/golang:1.23-alpine AS build

WORKDIR /src
COPY . .
ARG TARGETOS TARGETARCH CI_COMMIT_SHA CI_COMMIT_TAG CI_COMMIT_BRANCH
RUN apk add --no-cache -q just
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    just build-agent

FROM docker.io/alpine:3.21

RUN apk add -U --no-cache ca-certificates && \
  adduser -u 1000 -g 1000 crow -D && \
  mkdir -p /etc/crow && \
  chown -R crow:crow /etc/crow

ENV GODEBUG=netdns=go
# Internal setting do NOT change! Signals that crow is running inside a container
ENV WOODPECKER_IN_CONTAINER=true
EXPOSE 3000

COPY --from=build /src/dist/crow-agent /bin/

HEALTHCHECK CMD ["/bin/crow-agent", "ping"]
ENTRYPOINT ["/bin/crow-agent"]
