// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	pubsub "github.com/crowci/crow/v3/server/pubsub"
	mock "github.com/stretchr/testify/mock"
)

// Receiver is an autogenerated mock type for the Receiver type
type Receiver struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *Receiver) Execute(_a0 pubsub.Message) {
	_m.Called(_a0)
}

// NewReceiver creates a new instance of Receiver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReceiver(t interface {
	mock.TestingT
	Cleanup(func())
}) *Receiver {
	mock := &Receiver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
