// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeCrowServer is an autogenerated mock type for the UnsafeCrowServer type
type UnsafeCrowServer struct {
	mock.Mock
}

// mustEmbedUnimplementedCrowServer provides a mock function with given fields:
func (_m *UnsafeCrowServer) mustEmbedUnimplementedCrowServer() {
	_m.Called()
}

// NewUnsafeCrowServer creates a new instance of UnsafeCrowServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeCrowServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeCrowServer {
	mock := &UnsafeCrowServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
