// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeCrowAuthServer is an autogenerated mock type for the UnsafeCrowAuthServer type
type UnsafeCrowAuthServer struct {
	mock.Mock
}

// mustEmbedUnimplementedCrowAuthServer provides a mock function with given fields:
func (_m *UnsafeCrowAuthServer) mustEmbedUnimplementedCrowAuthServer() {
	_m.Called()
}

// NewUnsafeCrowAuthServer creates a new instance of UnsafeCrowAuthServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeCrowAuthServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeCrowAuthServer {
	mock := &UnsafeCrowAuthServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
